- hosts: all
  tasks:
      - name: "Configuring yum for docker software"
        yum_repository:
             file: "docker_repo"
             baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable/"
             name: "docker"
             gpgcheck: no
             description: "docker repo"

      - name: "Docker Installation"
        package:
             name: "docker-ce-18.09.1-3.el7.x86_64"
             state: present

      - name: "Starting Docker service"
        service:
             name: "docker"
             state: started
             enabled: yes

      - name: "Installing Python3"
        package:
             name: "python3"
             state: present


      - name: "Installing docker SDK"
        pip:
            name: "docker-py"
            state: present

      - name: "Creating directory In managed Node"
        file:
             path: "/root/webpages"
             state: directory

      - name: "Copy webpages to directory"
        copy:
             src: "/root/Ansible_playbooks/docker-webserver/webpages/index.html"
             dest: "/root/webpages"

      - name: "Pulling HTTPD Docker Container Image"
        docker_image:
             name: "httpd"
             source: pull
             state: present
      
      - name: "mas"       
        firewalld:
              masquerade: enable
              zone: public
              state: enabled
              permanent: yes

      - name: "Firewall restart"
        service:
              name: "firewalld"
              state: restarted 

      - name: "Launch httpd container"
        docker_container:
             name: "Webserver"
             image: "httpd"
             ports:
                   - "8081:80"
             state: started
             volumes:
                  - /root/webpages:/usr/local/apache2/htdocs/



